### PR TITLE
header, section and footer

### PR DESCRIPTION
**Pull request by mihrab34**

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 
### Hello @mihrab34,  👋

- fix this below previous requirement 
> On medium screen, the editor's picks section should have 2 columns. Please refer to the images below:
> 
> editor
> editor2

- (check this order because in your project it is Culture and travel  => More stories)
> In mobile view, let's arrange the sections in the correct order, Top story => More stories => Culture and travel => Featured stories => Opinion => Latest news. You can achieve this using bootstrap's order class. 

----
### Don't forgot to request for another code review 
----
### Happy coding 😄 
**Pon Muthu Selvam**
Feel free contact me on slack if you have any queries

**Comment by mihrab34** [comment]
The bootstrap order isn't working as intended on the more stories and culture$travel even after seeking suggestion @imhta on how to fix it.

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
## Hi Acintola!  
#### Please create feature branch with descriptive name, open pull request from feature branch with a descriptive name and submit another code review request!

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

**Comment by mihrab34** [comment]
Hi Anna-Myzukina,
I used Git-flow earlier with the intention of creating a feature branch but it was recommended that I use Github flow with one descriptive branch which I decided to do with my development branch.
I'm really confused, the video on pathright was on Git-flow which I did at first

**Comment by Anna-Myzukina** [comment]
> Hi Anna-Myzukina,
> I used Git-flow earlier with the intention of creating a feature branch but it was recommended that I use Github flow with one descriptive branch which I decided to do with my development branch.
> I'm really confused, the video on pathright was on Git-flow which I did at first

I contact you on slack)

**Review by Forison — COMMENTED** [review]
#### Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Good Job👋
## Project is approved👌
#### Happy coding🙂

**Pull request merged**
